[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 1.0
decorations = "None"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[colors.primary]
background = "#1E2326"
foreground = "#D3C6AA"

[colors.cursor]
text = "#1E2326"
cursor = "#D3C6AA"

[colors.selection]
text = "#D3C6AA"
background = "#4F5B58"

[colors.normal]
black   = "#3C474D"
red     = "#E67E80"
green   = "#A7C080"
yellow  = "#DBBC7F"
blue    = "#7FBBB3"
magenta = "#D699B6"
cyan    = "#83C092"
white   = "#D3C6AA"

[colors.bright]
black   = "#56635F"
red     = "#F85552"
green   = "#A7C080"
yellow  = "#DDB26F"
blue    = "#7FBBB3"
magenta = "#D699B6"
cyan    = "#83C092"
white   = "#E6DFC8"
