# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7bdfe212-94b4-4347-9ebd-5e940c0ed92a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DDC4-180E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-efd7a52d-abf2-4ead-84a4-99e426a3229d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-efd7a52d-abf2-4ead-84a4-99e426a3229d".device = "/dev/disk/by-uuid/efd7a52d-abf2-4ead-84a4-99e426a3229d";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b43a461d-e231-48fb-813a-b295a2cc08e1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
