# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1de4b14c-0287-4662-81d1-d7878469ab60";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/20E3-050B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-af5a6c2b-f524-4f08-948e-7124fc37303d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-af5a6c2b-f524-4f08-948e-7124fc37303d".device = "/dev/disk/by-uuid/af5a6c2b-f524-4f08-948e-7124fc37303d";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b7ded8aa-a49e-40ae-b629-1f723cb6d156"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
