# BACKGROUND
background {
    monitor =
    path = screenshot

    blur_passes = 2
    contrast = 1
    brightness = 0.75
    vibrancy = 0.15
    vibrancy_darkness = 0.25
}

# GENERAL
general {
    hide_cursor = true
    ignore_empty_input = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 180, 55

    outline_thickness = 2

    dots_size = 0.4
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgba(180, 190, 254, 0.90)  # Lavender
    inner_color = rgba(30, 30, 46, 0.85)     # Base

    font_color = rgb(205, 214, 244)          # Text

    font_family = JetBrainsMono Nerd Font Mono

    fade_on_empty = true
    rounding = 12

    check_color = rgb(166, 227, 161)         # Green

    fail_text = Wrong password
    fail_color = #f38ba8                      # Red

    placeholder_text = Enter password
    placeholder_color = #7f849c              # Overlay1

    hide_input = false

    position = 0, -580
    halign = center
    valign = center
}

# TIME
label {
    monitor =

    text = cmd[update:1000] echo "$(date +'%H:%M')"

    color = rgba(205, 214, 244, 0.95)

    font_size = 300
    font_family = JetBrainsMono Nerd Font

    halign = center
    valign = center
}
