background {
    monitor =
    path = screenshot

    blur_passes = 4
    contrast = 1
    brightness = 0.45
    vibrancy = 0
    vibrancy_darkness = 0
}

general {
    hide_cursor = true
    ignore_empty_input = true
}

input-field {
    monitor =

    size = 320, 55
    outline_thickness = 2

    dots_size = 0.28
    dots_spacing = 0.22
    dots_center = true

    outer_color = rgb(9ece6a)

    inner_color = rgba(26,27,38,0.80)

    font_color = rgb(c0caf5)

    placeholder_text = Password...

    check_color = rgb(9ece6a)
    fail_color = rgb(f7768e)

    fade_on_empty = false
    rounding = 18

    position = 0, -200
    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] echo "$(date +'%H:%M')"

    color = rgb(c0caf5)

    font_size = 200
    font_family = JetBrainsMono Nerd Font

    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:60000] echo "$(date +"%A, %d %B")"

    color = rgb(e0af68)

    font_size = 32
    font_family = JetBrainsMono Nerd Font

    position = 0, -100
    halign = center
    valign = center
}
