{ pkgs, ... }:

{
    home.packages = with pkgs; [
        fastfetch
        htop
        brightnessctl
        wl-clipboard
        waybar
        fuzzel
        grim
        slurp
        ripgrep
        nixpkgs-fmt
        nodejs
        gcc
        glibc.dev
        zathura
        zathuraPkgs.zathura_pdf_mupdf
        unzip
        gnutar
        gzip
        fzf
        qbittorrent
        go
        mpv
        obsidian
        obs-studio
        imv
        gnumake
        pkg-config
        tomato-c
        syncthing
        mako
        libnotify
        nautilus
        ffmpegthumbnailer
        swaybg
        libresprite
        hyprlock
        hypridle
        python3
        jdk
	];
}
