{ pkgs, ... }:

{
    home.packages = with pkgs; [
        fastfetch
        htop
        brightnessctl
        wl-clipboard
        waybar
        fuzzel
        brave
        grim
        slurp
        ripgrep
        nixpkgs-fmt
        gcc
        cmake
        obsidian
        glibc.dev
        unzip
        gnutar
        gzip
        fzf
        go
        mpv
        imv
        obs-studio
        gnumake
        pkg-config
        syncthing
        mako
        libnotify
        thunar
        thunar-archive-plugin
        thunar-volman
        thunar-media-tags-plugin
        ffmpegthumbnailer
	    tumbler
        swaybg
        libresprite
        hyprlock
        hypridle
	    wlr-randr
        python3
        qbittorrent
        logisim-evolution
	];
}
