{ pkgs, ... }:

{
    home.packages = with pkgs; [
        fastfetch
        htop
        brightnessctl
        wl-clipboard
        waybar
        fuzzel
        grim
        slurp
        ripgrep
        nixpkgs-fmt
        gcc
        glibc.dev
        unzip
        gnutar
        gzip
        fzf
        go
        mpv
        imv
        gnumake
        pkg-config
        syncthing
        mako
        libnotify
        xfce.thunar
        xfce.thunar-archive-plugin
        xfce.thunar-volman
        xfce.thunar-media-tags-plugin
        ffmpegthumbnailer
        swaybg
        libresprite
        hyprlock
        hypridle
        python3
        jdk
	];
}
