# Font
font_family JetBrainsMono Nerd Font
font_size 14

# Window decoration
hide_window_decorations yes

# Padding
window_padding_width 7

# Cursor
cursor_shape block
cursor_blink_interval 0
cursor_trail 5
cursor_trail_decay 0.08 0.3

# Scrolling
scrollback_lines 50000

# No bells
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no
bell_on_tab no
command_on_bell none

# Don't ask when closing
confirm_os_window_close 0

# Misc
copy_on_select yes
strip_trailing_spaces smart
mouse_hide_wait 2.0
remember_window_size no

# Performance
sync_to_monitor yes
repaint_delay 10
input_delay 3

# Tabs
tab_bar_style powerline
tab_powerline_style slanted

# Colors
background_opacity 1.0

foreground            #d3c6aa
background            #1e2326
selection_foreground  #d3c6aa
selection_background  #374145
url_color             #7fbbb3
cursor                #a7c080
cursor_text_color     #1e2326

# black
color0   #4b565c
color8   #5c6a72

# red
color1   #e67e80
color9   #f85552

# green
color2   #a7c080
color10  #b5c99a

# yellow
color3   #dbbc7f
color11  #e69875

# blue
color4   #7fbbb3
color12  #83c092

# magenta
color5   #d699b6
color13  #e67e80

# cyan
color6   #83c092
color14  #9fd3c7

# white
color7   #d3c6aa
color15  #ffffff
