# Font
font_family JetBrainsMono Nerd Font
font_size 14

# Padding
window_padding_width 7

# Cursor
cursor_shape block
cursor_blink_interval 0
cursor_trail 5
cursor_trail_decay 0.08 0.3

# Scrolling
scrollback_lines 50000

# No bells
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no
bell_on_tab no
command_on_bell none

# Don't ask when closing
confirm_os_window_close 0

# Misc
copy_on_select yes
strip_trailing_spaces smart
mouse_hide_wait 2.0
remember_window_size no

# Performance
sync_to_monitor yes
repaint_delay 10
input_delay 3

# Tabs
tab_bar_style powerline
tab_powerline_style slanted

# colors
background_opacity 1.0
foreground            #d3c6aa
background            #1e2326
selection_foreground  #3c474d
selection_background  #525c62
url_color             #415c6d
cursor                #7fbbb3

# black
color0   #4a555b
color8   #525c62

# red
color1   #e68183
color9   #e68183

# green
color2   #a7c080
color10  #a7c080

# yellow
color3   #dbbc7f
color11  #dbbc7f

# blue
color4  #7fbbb3
color12 #7fbbb3

# magenta
color5   #d699b6
color13  #d699b6

# cyan
color6   #83c092
color14  #83c092

# white
color7   #d8caac
color15  #d8caac
