# Font
font_family Iosevka Nerd Font
font_size 15

# Padding
window_padding_width 7

# Cursor
cursor_shape block
cursor_blink_interval 0
cursor_trail 5
cursor_trail_decay 0.08 0.3

# Scrolling
scrollback_lines 50000

# No bells
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no
bell_on_tab no
command_on_bell none

# Don't ask when closing
confirm_os_window_close 0

# Misc
copy_on_select yes
strip_trailing_spaces smart
mouse_hide_wait 2.0
remember_window_size no

# Performance
sync_to_monitor yes
repaint_delay 10
input_delay 3

# Tabs
tab_bar_style powerline
tab_powerline_style slanted

# colors
background_opacity 1.0
background #1d1f21
foreground #c4c8c5
cursor #c4c8c5
selection_background #363a41
color0 #000000
color8 #373a41
color1 #cc6666
color9 #cc6666
color2 #b5bd68
color10 #b5bd68
color3 #f0c574
color11 #f0c574
color4 #80a1bd
color12 #80a1bd
color5 #b294ba
color13 #b294ba
color6 #8abdb6
color14 #8abdb6
color7 #fffefe
color15 #fffefe
selection_foreground #1d1f21

active_tab_foreground   #eeeeee
active_tab_background   #363a41
inactive_tab_foreground #c4c8c5
inactive_tab_background #17191a
